name: Extraction PE
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: --name my_mongo -v /home/user/projet/sample_training:/data/db
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
          python-version: 3.x
    - name: Install Python libraries
      run: |
        pip3 install pandas==1.5.3 requests pymongo
    - name: Exec python PE
      env:
         api_key: ${{ secrets.API_PE_KEY }}
         api_id_client: ${{ secrets.API_PE_CLIENT }}
      run: |
        python3 PE_extraction.py
